### ISSUE TITLE
0 on all lines

### ISSUE THREAD

**Issue by Kausta** [hellerve/e#14]
On WSL Ubuntu 16.04, all lines start ` 0`, and the cursor is one/two to the left of where it should be.

**Comment by hellerve** [comment]
Do you mean the column counter?

**Comment by ghost** [comment]
Can also confirm this issue.

Sample image supplied below:
![e-issue](https://user-images.githubusercontent.com/24823300/30104417-7000033c-92ed-11e7-84f3-c3b7b91712ea.png)
The zero at the start of the line was auto inserted and new lines will also start with zero.
The cursor is actually at the very end of the line but is always back 1-2 (this does vary as @Kausta has reported as well) characters visually.

**Comment by hellerve** [comment]
Oh wow, that looks like an ANSI escape sequence gone astray. Will investigate.

**Comment by hellerve** [comment]
Okay, another one of these "why did it work on OS X in the first place" bugs. Thanks for reporting, should be fixed by the latest commit.

**Comment by Kausta** [comment]
Latest commit fixed it and its working now.

**Comment by ghost** [comment]
Can confirm fixed.
