### ISSUE TITLE
Deal with syntax errors in coloring regex files 

### ISSUE THREAD

**Issue by benob** [hellerve/e#33]
If there are syntax errors in coloring files (regcomp returns a non-null value), e exits abruptly without a message.
https://github.com/hellerve/e/blob/0e6ed8367b75805ff7341b528a0ac3c68c2a00b9/src/syntax.c#L31

**Comment by hellerve** [comment]
Thanks for reporting this!

I briefly talked about this in #13. I will write a better error handler at some point, but at the moment I’m sadly a bit tied up by work.

**Comment by hellerve** [comment]
I worked on this a bit. Now it at least prints an error message before dying its graceless death.

Example: `Syntax: encountered an error in pattern "foobar(": parentheses not balanced`

It still leaks memory, though, which is not great (euphemistically speaking).

**Comment by hellerve** [comment]
I’ve openend a PR on this issue. @benob: could you kindly review whether this is what you would want as per error handling?

**Comment by benob** [comment]
It's great, thanks. Maybe a mention of the file name and line number would make it even more user friendly ;)

**Comment by hellerve** [comment]
Done! :)
